spring:
  profiles: 
    active: dev

---
server:
  port: 8004

mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    cache-enabled: true

spring:
  profiles: dev
  application:
    name: provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123123

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---
server:
  port: 8004

mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    cache-enabled: true

spring:
  profiles: test
  application:
    name: provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123123

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/